version: "3"

services:

  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports: ["5432:5432"]
    expose: ["5432"]

  web:
    build: .
    ports: ["3000:3000"]
    tty: true
    stdin_open: true
    expose: ["3000"]
    environment:
      - RAILS_ENV=development
      - PG_HOST=db
      - PG_USERNAME=user
      - PG_PASSWORD=password
    links:
      - db
    volumes:
      - .:/poc-ruby
    depends_on:
      - db
